"""Add organizatoin

Revision ID: 50e609a53dcb
Revises: 6cd70e798b82
Create Date: 2019-05-30 21:42:02.164494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50e609a53dcb"
down_revision = "6cd70e798b82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("name", name=op.f("uq_organizations_name")),
    )
    op.add_column("users", sa.Column("organization_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_organization_id_organizations"),
        "users",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_organization_id_organizations"), "users", type_="foreignkey"
    )
    op.drop_column("users", "organization_id")
    op.drop_table("organizations")
    # ### end Alembic commands ###
