"""Add timestamp columns

Revision ID: 88075d0ff4d8
Revises: 4b4a426227ee
Create Date: 2019-06-01 16:45:30.841077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88075d0ff4d8'
down_revision = '4b4a426227ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organizations', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organizations', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'created_at')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
