"""empty message

Revision ID: ba541be05848
Revises: 88075d0ff4d8
Create Date: 2019-06-01 16:52:29.732885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba541be05848"
down_revision = "88075d0ff4d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("begins_at", sa.TIMESTAMP(timezone=True), nullable=False)
    )
    op.add_column(
        "events", sa.Column("ends_at", sa.TIMESTAMP(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "ends_at")
    op.drop_column("events", "begins_at")
    # ### end Alembic commands ###
